### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by zhizdev** [arpruss/brainflex#1]
Dear Arpruss, 

I really like your work here, but I have a question on when the program is recording raw data, it records it in .thg file. How do I see the thg file?

Thanks

**Comment by arpruss** [comment]
I think it's just a text file. You can also load it into the brainflex program using the load-from-data-file in the dropdown list. (Sorry that program is not very friendly. I don't know how to do java non-android gui stuff.)

**Comment by zhizdev** [comment]
Thanks for the quick reply! 
I am actually working on a project in which I want to upload to github, but right now I need to collect the eeg data into a database file such as .csv so I can analyze the data. 
The official research kit from neurosky is too expensive for me to buy:( So I am trying to find an alternative. 
Also, if you are interested, I would like to share my project with you through email to get some feedback. That would mean a lot to me:)
Thanks

**Comment by arpruss** [comment]
The format of the thg file is very simple. Lines starting with R are raw data, sampled 512 times per second. Lines starting with P are processed data (the data for the various bands the Neurosky device reports). Lines starting with M are marker locations if you inserted markers by pressing keys while the brainflex code is running.

I am happy to share ideas.

**Comment by zhizdev** [comment]
How can I read the lines of the .thg file?
When I load it back to mindflex i get 
"
class mobi.omegacentauri.brainflex.FileDataLink
Connecting
Connected
End of data" 

Can I get the rough location of the .java file where the lines are being recorded?
For example Mark.java or options.java...

Thanks

**Comment by zhizdev** [comment]
Right now I am inserting a script within mindflex that writes the values meditation and attention values into a file through apache commons io library. 

```
String attentionVs = "" + attentionV;
        String meditationVs = "" + meditationV;
        File fileattentionV = new File("eegvar.php");
        String fileContext2 = FileUtils.readFileToString(fileattentionV);
        fileContext2 = "[{\"meditation\": \"" + meditationV + "\", \"attention\": \""+attentionV+"\"}]";
        FileUtils.write(fileattentionV, fileContext2);
```

I am not sure where I can get the variables that updates 512 times per second to write into a file.

**Comment by shadowninjazx** [comment]
String attentionVs = "" + attentionV;
		String meditationVs = "" + meditationV;
		File fileattentionV = new File("eegvar.php");
		String fileContext2 = FileUtils.readFileToString(fileattentionV);
		fileContext2 = "[{\"meditation\": \"" + meditationV + "\", \"attention\": \""+attentionV+"\"}]";
		FileUtils.write(fileattentionV, fileContext2);
